name: Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install yarn
        run: sudo npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Fix audit
        run: npm_config_yes=true npx yarn-audit-fix

      - name: Build docs
        run: yarn build

      - name: Build inner HTMLs
        run: yarn build:inner

      - name: Setup GitHub Pages
        if: github.event_name == 'push'
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v2
        with:
            path: build

      - name: Deploy
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v2
